source 'https://rubygems.org'

gem 'sinatra', '~>1.4'
gem 'sinatra-contrib', '~>1.4'
gem 'puma', '3.6.0'
gem 'json', '~>1.8'
gem 'json-schema', '~>2.5'
gem 'logstash-logger', '~>0.19.2'
gem 'bunny', '~>2.3.1'
gem 'rake', '~>11.3.0'

group :development do
	gem 'rerun'
end

group :doc do
	gem 'yard'
end

gem 'cassandra-cql', '~>1.2.2'
#gem 'sinatra-gkauth', '~>0.3.0', path: '../sinatra-gkauth-gem'
