require 'yard'

namespace(:db) do
  task(:load_config)
end

def config
  @config ||= YAML.load_file File.join(rakefile_directory, 'config/config.yml')
end

task :start do
	conf = File.expand_path('config/puma.rb', File.dirname(__FILE__))
	exec("puma -C #{conf}")
end

YARD::Rake::YardocTask.new do |t|
	t.files = ['main.rb', 'helpers/*.rb', 'routes/*.rb']
end

