source 'https://rubygems.org'

gem 'sinatra', '~>1.4'
gem 'sinatra-contrib', '~>1.4'
gem 'puma', '3.6.0'
gem 'json', '~>1.8'
gem 'json-schema', '~>2.5'
gem 'rake', '~>11.3.0'
gem 'rest-client', '~>2.0'
gem 'mongoid', '~>4.0' # MongoDB driver

group :development do
	gem 'rerun'
	# Database
end

group :doc do
	gem 'yard', '~>0.8'
end

gem 'fluent-logger-sinatra', '~>0.2.0', path: '../fluent-logger-sinatra'
