require 'yard'

desc 'Start the service'
task :start do
	conf = File.expand_path('config/puma.rb', File.dirname(__FILE__))
	exec("puma -C #{conf}")
end

namespace :db do
  task :load_config do
    require './main'
  end
end

YARD::Rake::YardocTask.new do |t|
  t.files = ['main.rb', 'helpers/*.rb', 'routes/*.rb']
end
