source 'https://rubygems.org'

gem 'sinatra', '~>1.4'
gem 'sinatra-contrib', '~>1.4'
gem 'puma', '3.6.0'
gem 'json', '~>1.8'
gem 'json-schema', '~>2.5'
gem 'rest-client', '~>2.0'
gem 'logstash-logger', '~>0.19.1'
gem 'bunny', '~>2.3.1'
gem 'activerecord'
gem 'sinatra-activerecord', '~>2.0.10'
gem 'sqlite3'
gem 'rake'

group :development do
	gem 'rerun'
end

group :doc do
	gem 'yard', '~>0.8'
end

gem 'mongoid', '~>4.0' # MongoDB driver
#gem 'sinatra-gkauth', '~>0.3.0', path: '../sinatra-gkauth-gem'
