source 'https://rubygems.org'

gem 'sinatra', '~>1.4'
gem 'sinatra-contrib', '~>1.4'
gem 'puma', '3.6.0'
gem 'json', '~>1.8'
gem 'json-schema', '~>2.5'
gem 'rest-client', '~>2.0.0'
gem 'logstash-logger', '~>0.19.1'

group :development, :test do
  gem 'webmock', '2.1.0'
  gem 'rspec', '3.5.0'
  gem 'rack-test', '0.6.3'
  gem 'rspec-its', '1.2.0'
  gem 'rerun'
  gem 'database_cleaner'
  gem 'factory_girl'
end

group :doc do
	gem 'yard', '~>0.8'
end

# Database
gem 'mongoid', '~>4.0' # MongoDB driver
gem 'mongoid-pagination', '~>0.2' # Pagination library

gem 'sinatra-gkauth', '~>0.3.0', path: '../sinatra-gkauth-gem'
