require 'yard'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new :specs do |task|
	task.pattern = Dir['spec/*_spec.rb']
end

task :default => ['specs']

desc 'Start the service'
task :start do
	conf = File.expand_path('config.ru', File.dirname(__FILE__))
	conf2 = File.expand_path('config/config.yml', File.dirname(__FILE__))
	exec("thin -C #{conf2} -R #{conf} --debug start")
end

YARD::Rake::YardocTask.new do |t|
	t.files = ['main.rb', 'helpers/ns.rb', 'routes/ns.rb']
end

namespace :db do
	task :load_config do
		require './main'
	end
end

task :headers do
  require 'rubygems'
  require 'copyright_header'

  args = {
    :license => 'ASL2',
    :copyright_software => 'TeNOR',
    :copyright_software_description => "NS Catalogue",
    :copyright_holders => ['i2CAT Foundation'],
    :copyright_years => ['2014-2016'],
    :add_path => 'routes:helpers',
    :output_dir => '.'
  }

  command_line = CopyrightHeader::CommandLine.new( args )
  command_line.execute
end
