source 'https://rubygems.org'

gem 'sinatra', '~>1.4'
gem 'thin', '~>1.6'
gem 'json', '~>1.8'
gem 'sinatra-contrib', '~>1.4'
gem 'nokogiri', '~>1.6'
gem 'json-schema', '~>2.5'
gem 'rest-client', '~>1.8'
gem 'logstash-logger'

group :development do
	gem 'rerun'
end

group :doc do
	gem 'yard', '~>0.8'
end

#gem 'gk-auth', '~>0.0.2', path: '../gk-auth-gem'
#gem 'test', '~>0.1.1', path: '../test'
gem 'sinatra-gkauth', '~>0.2.0', path: '../sinatra-gkauth-gem'
