source 'https://rubygems.org'

gem 'sinatra', '~>1.4'
gem 'sinatra-contrib', '~>1.4'
gem 'puma', '3.6.0'
gem 'json', '~>1.8'
gem 'json-schema', '~>2.5'
gem 'logstash-logger', '~>0.19.2'

# Gatekeeper auth gem
gem 'sinatra-gkauth', '~>0.3.0', path: '../sinatra-gkauth-gem'

group :development, :test do
	gem 'rerun'
	gem 'rspec'
	gem 'rack-test'
end

group :doc do
	gem 'yard', '~>0.8'
end
