source 'https://rubygems.org'

gem 'sinatra', '~>1.4'
gem 'sinatra-contrib', '~>1.4'
gem 'puma', '3.6.0'
gem 'json', '~>1.8'
gem 'json-schema', '~>2.5'
gem 'rake', '~>11.3.0'
gem 'rest-client', '~>2.0'
gem 'mongoid', '~>4.0' # MongoDB driver

group :development do
	gem 'rerun'
end

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'webmock'
  gem 'database_cleaner'
  gem 'factory_girl'
end

group :doc do
	gem 'yard', '~>0.8'
end

gem 'sinatra-gkauth', '~>0.3.0', path: '../sinatra-gkauth-gem'
gem 'fluent-logger-sinatra', '~>0.2.0', path: '../fluent-logger-sinatra'
