source 'https://rubygems.org'

gem 'sinatra', '~>1.4'
gem 'sinatra-contrib', '~>1.4'
gem 'puma', '3.6.0'
gem 'json', '~>1.8'
gem 'json-schema', '~>2.5'
gem 'nokogiri', '~>1.6'
gem 'rest-client', '~>1.8'
gem 'logstash-logger', '~>0.19.1'

group :development, :test do
	gem 'rerun'
	gem 'rspec'
	gem 'rack-test'
	gem 'database_cleaner'
	gem 'factory_girl'
	gem 'webmock'
end

group :doc do
	gem 'yard', '~>0.8'
end

# Database
gem 'mongoid', '~>4.0' # MongoDB driver
gem 'mongoid-pagination', '~>0.2' # Pagination library
gem 'mongoid-versioning', '~>1.2' # Versioning library

# Gatekeeper auth gem
gem 'sinatra-gkauth', '~>0.3.0', path: '../sinatra-gkauth-gem'