require 'yard'
require 'yaml'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new :specs do |task|
	task.pattern = Dir['spec/*_spec.rb']
end

task :default => ['specs']

desc 'Start the service'
task :start do
	conf = File.expand_path('config/puma.rb', File.dirname(__FILE__))
	exec("puma -C #{conf}")
end

YARD::Rake::YardocTask.new do |t|
	t.files = ['main.rb', 'helpers/vnfs.rb', 'routes/vnfs.rb', 'models/vnf.rb']
end

namespace :db do
	task :load_config do
		require './main'
	end
end