source 'https://rubygems.org'

gem 'sinatra', '~>1.4'
gem 'sinatra-contrib', '~>1.4'
gem 'puma', '3.6.0'
gem 'json', '~>1.8'
gem 'json-schema', '~>2.5'
gem 'fluent-logger-sinatra', '0.1.2'
gem 'rake', '~>11.3.0'

group :development, :test do
	gem 'rerun'
	gem 'rspec'
	gem 'rack-test'
	gem 'database_cleaner'
	gem 'factory_girl'
end

group :development do
	gem 'rerun'
end

group :doc do
	gem 'yard', '~>0.8'
end

# Gatekeeper auth gem
gem 'sinatra-gkauth', '~>0.3.1', path: '../sinatra-gkauth-gem'
