source 'https://rubygems.org'

gem 'sinatra', '~>1.4'
gem 'sinatra-contrib', '~>1.4'
gem 'puma', '3.6.0'
gem 'json', '~>1.8'
gem 'json-schema', '~>2.5'
gem 'rest-client', '~>1.8'
gem 'logstash-logger', '~>0.19.1'
gem 'sinatra-activerecord', '~>2.0.10'

group :development do
	gem 'rerun'
end

group :doc do
	gem 'yard', '~>0.8'
end