require 'yard'
require 'yaml'

def config
	@config ||= YAML.load_file File.join(rakefile_directory, 'config/config.yml')
end

desc "Start The Application"
task :start do
	conf = File.expand_path('config/puma.rb', File.dirname(__FILE__))
	exec("puma -C #{conf}")
end

YARD::Rake::YardocTask.new do |t|
	t.files = ['main.rb', 'helpers/init.rb', 'routes/init.rb']
end

