source 'https://rubygems.org'

gem 'sinatra', '~>1.4'
gem 'thin', '~>1.6'
gem 'json', '~>1.8'
gem 'sinatra-contrib', '~>1.4'
gem 'nokogiri', '~>1.6'
gem 'json-schema', '~>2.5'
gem 'rest-client', '~>1.8'
gem 'logstash-logger'

# Gatekeeper auth gem
gem 'sinatra-gkauth', '~>0.2.0', path: '../sinatra-gkauth-gem'

group :development do
	gem 'rerun'
end

group :test do
  gem 'rspec'
  gem 'rack-test'
end

group :doc do
	gem 'yard', '~>0.8'
end

# Database
gem 'mongoid', '~>4.0' # MongoDB driver