require 'yard'
require 'yaml'

task :start do
	conf = File.expand_path('config/puma.rb', File.dirname(__FILE__))
	exec("puma -C #{conf}")
end

YARD::Rake::YardocTask.new do |t|
	t.files = ['main.rb', 'helpers/vnf.rb', 'routes/*.rb']
end