require 'yard'
require 'yaml'

task :start do
	conf = File.expand_path('config.ru', File.dirname(__FILE__))
	conf2 = File.expand_path('config/config.yml', File.dirname(__FILE__))
	exec("thin -C #{conf2} -R #{conf} --debug start")
end

YARD::Rake::YardocTask.new do |t|
	t.files = ['main.rb', 'helpers/vnf.rb', 'routes/vnf.rb']
end