source 'https://rubygems.org'

gem 'sinatra', '~>1.4'
gem 'sinatra-contrib', '~>1.4'
gem 'puma', '3.6.0'
gem 'json', '~>1.8'
gem 'json-schema', '~>2.5'
gem 'rake', '~>11.3.0'
gem 'rest-client', '~>2.0'
gem 'mongoid', '~>4.0' # MongoDB driver
gem 'bunny', '~>2.3.1'

group :development, :test do
	gem 'webmock', '2.1.0'
  gem 'rspec', '3.5.0'
  gem 'rack-test', '0.6.3'
  gem 'rspec-its', '1.2.0'
  gem 'rerun'
  gem 'database_cleaner'
  gem 'factory_girl'
end

group :doc do
	gem 'yard', '~>0.8'
end

gem 'sinatra-gkauth', '~>0.4.0', path: '../sinatra-gkauth-gem'
gem 'fluent-logger-sinatra', '~>0.2.0', path: '../fluent-logger-sinatra'
