source 'https://rubygems.org'
ruby "1.9.3"

gem 'sinatra'
gem 'thin'
gem 'json', "1.8.3"
gem 'sinatra-contrib'
gem 'nokogiri'
gem 'json-schema'
gem 'rest-client'
gem 'rake'

group :development do
	gem 'rerun'
end

group :doc do
	gem 'yard', '~>0.8'
end
